// Discovery: find lab projects in the Virtual Company GitHub org and PIN each to an exact commit in data/lock.json.
// This is the only place the org is read. The site build never follows branches - it only fetches the pinned commits.
// Run by .github/workflows/sync.yml on a schedule (and by hand: node scripts/discover.mjs). Needs no secret for public repos.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { validateManifest } from "./lib/validate.mjs";

const cfg = JSON.parse(readFileSync("lab.config.json", "utf8"));
const blocklist = existsSync("blocklist.json") ? JSON.parse(readFileSync("blocklist.json", "utf8")) : [];
const approved = existsSync("approved.json") ? JSON.parse(readFileSync("approved.json", "utf8")) : [];
const lockPath = "data/lock.json";
const lock = existsSync(lockPath) ? JSON.parse(readFileSync(lockPath, "utf8")) : { projects: [] };
const token = process.env.LAB_GH_TOKEN || process.env.GITHUB_TOKEN || "";
const H = { "User-Agent": "juskowicz-lab-sync", Accept: "application/vnd.github+json", ...(token ? { Authorization: `Bearer ${token}` } : {}) };

async function gh(path, accept) {
  const r = await fetch("https://api.github.com" + path, { headers: accept ? { ...H, Accept: accept } : H });
  if (!r.ok) throw new Error(`${path} -> ${r.status}`);
  return accept ? r.text() : r.json();
}

const repos = [];
for (let page = 1; page <= 5; page++) {
  const batch = await gh(`/orgs/${cfg.org}/repos?per_page=100&page=${page}&sort=pushed&type=${token ? "all" : "public"}`);
  repos.push(...batch);
  if (batch.length < 100) break;
}
console.log(`org ${cfg.org}: ${repos.length} repos visible`);

const next = [];
const taken = new Set();
for (const r of repos) {
  const id = r.full_name;
  if (r.archived || r.fork || r.disabled) continue;
  if (!(r.topics || []).includes(cfg.topic)) continue;
  if (blocklist.includes(id) || blocklist.includes(r.name)) { console.log("blocked:", id); continue; }
  if (cfg.approval === "manual" && !approved.includes(id) && !approved.includes(r.name)) { console.log("awaiting approval:", id); continue; }
  const prev = lock.projects.find((p) => p.repo === id);
  if (prev && prev.hold) { next.push(prev); taken.add(prev.slug); continue; } // Michael pinned this one
  try {
    const sha = (await gh(`/repos/${id}/commits/${r.default_branch}`)).sha;
    const raw = JSON.parse(await gh(`/repos/${id}/contents/lab.json?ref=${sha}`, "application/vnd.github.raw"));
    const v = validateManifest(raw, { repoName: r.name });
    if (!v.ok) { console.log(`skip ${id}: ${v.errors.join("; ")}`); continue; }
    if (taken.has(v.manifest.slug)) { console.log(`skip ${id}: slug ${v.manifest.slug} already taken`); continue; }
    taken.add(v.manifest.slug);
    next.push({ slug: v.manifest.slug, repo: id, sha, title: v.manifest.title, updated: r.pushed_at, firstSeen: prev?.firstSeen || new Date().toISOString() });
    console.log(prev?.sha === sha ? `same   ${id}` : `PIN    ${id} @ ${sha.slice(0, 7)}`);
  } catch (e) { console.log(`skip ${id}: ${e.message}`); }
}
next.sort((a, b) => (b.updated || "").localeCompare(a.updated || ""));
const out = { note: "Generated by scripts/discover.mjs. Add \"hold\": true to an entry to freeze it at its sha.", projects: next.slice(0, cfg.limits.maxProjects) };
const changed = JSON.stringify(out.projects.map(({ updated, ...p }) => p)) !== JSON.stringify(lock.projects.map(({ updated, ...p }) => p));
if (changed) { writeFileSync(lockPath, JSON.stringify(out, null, 2) + "\n"); console.log("lock updated"); } else console.log("lock unchanged");
